"""Shared visual language for the Streamlit app.

Centralises palette, Plotly template, and a small set of markup helpers so
every page looks like part of the same product rather than a notebook wrapper.
Each page that wants the polished look calls :func:`apply_page_theme` once at
the top (after ``st.set_page_config``); downstream renders use ``page_intro``,
``insight_row``, ``metric_card``, ``section_header``, and ``status_pill``.
"""
from __future__ import annotations
from dataclasses import dataclass
from typing import Iterable, Optional

import streamlit as st
import plotly.graph_objects as go
import plotly.io as pio


# ---------------------------------------------------------------------------
# Palette
# ---------------------------------------------------------------------------
PALETTE = {
    'brand':        '#2c5fa8',
    'brand_soft':   '#3a78b8',
    'brand_deep':   '#1e4d82',
    'surface':      '#ffffff',
    'surface_2':    '#f7f8fb',
    'surface_card': '#fbfcfd',
    'border':       '#eef0f5',
    'text':         '#1f2933',
    'text_muted':   '#5b6b82',
    'ok_fg':        '#1e7e5a',
    'ok_bg':        '#eef6f2',
    'warn_fg':      '#a36a0a',
    'warn_bg':      '#fbf5e6',
    'alert_fg':     '#a63a3a',
    'alert_bg':     '#fbeaea',
    'note_fg':      '#3a78b8',
    'note_bg':      '#f0f4fa',
    'neutral_fg':   '#5b6b82',
    'neutral_bg':   '#f4f6fa',
}

GITHUB_URL = 'https://github.com/Li-Shen-Clark/pricing-promotion-decision-engine'
AUTHOR_NAME = 'Li Shen, Clark University'
AUTHOR_AFFILIATION = ''

SIDEBAR_PAGES = [
    ('app.py', 'Overview'),
    ('pages/1_Evidence.py', 'Evidence'),
    ('pages/2_Simulate.py', 'Simulate'),
    ('pages/3_Optimize.py', 'Optimize'),
    ('pages/4_Validate.py', 'Validate'),
    ('pages/5_Boundaries.py', 'Boundaries'),
    ('pages/6_Upload.py', 'Upload'),
]

_TONE_CLASSES = {
    'ok':      ('ok_fg',      'ok_bg'),
    'warn':    ('warn_fg',    'warn_bg'),
    'alert':   ('alert_fg',   'alert_bg'),
    'note':    ('note_fg',    'note_bg'),
    'brand':   ('brand',      'surface_card'),
    'neutral': ('neutral_fg', 'neutral_bg'),
}


# ---------------------------------------------------------------------------
# Plotly template
# ---------------------------------------------------------------------------
_COLORWAY = [
    PALETTE['brand'],
    PALETTE['ok_fg'],
    PALETTE['warn_fg'],
    PALETTE['alert_fg'],
    PALETTE['brand_soft'],
    PALETTE['neutral_fg'],
]

_PRICING_TEMPLATE = go.layout.Template(
    layout=go.Layout(
        font=dict(family='-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
                  color=PALETTE['text'], size=12),
        colorway=_COLORWAY,
        paper_bgcolor='rgba(0,0,0,0)',
        plot_bgcolor='rgba(0,0,0,0)',
        xaxis=dict(showgrid=True, gridcolor=PALETTE['border'],
                   zeroline=False, ticks='outside',
                   tickcolor=PALETTE['border']),
        yaxis=dict(showgrid=True, gridcolor=PALETTE['border'],
                   zeroline=False, ticks='outside',
                   tickcolor=PALETTE['border']),
        legend=dict(bgcolor='rgba(0,0,0,0)', borderwidth=0,
                    font=dict(color=PALETTE['text'])),
        margin=dict(l=12, r=12, t=32, b=12),
    )
)


def register_plotly_template() -> None:
    """Register + set the pricing-engine template as the default."""
    pio.templates['pricing_engine'] = _PRICING_TEMPLATE
    pio.templates.default = 'pricing_engine'


# ---------------------------------------------------------------------------
# CSS
# ---------------------------------------------------------------------------
def _css() -> str:
    p = PALETTE
    return f"""
    <style>
      :root {{
        --brand: {p['brand']};
        --brand-soft: {p['brand_soft']};
        --brand-deep: {p['brand_deep']};
        --surface: {p['surface']};
        --surface-2: {p['surface_2']};
        --surface-card: {p['surface_card']};
        --border: {p['border']};
        --text: {p['text']};
        --text-muted: {p['text_muted']};
      }}

      .block-container {{ padding-top: 1.8rem; }}

      /* Hide Streamlit's autogenerated page list so the entry page does not
         appear as "app". The custom page links below use product labels. */
      [data-testid="stSidebarNav"] {{ display: none; }}
      [data-testid="stSidebarUserContent"] {{
          min-height: 100vh;
          display: flex;
          flex-direction: column;
      }}

      h1, h2, h3, h4 {{ color: var(--text); letter-spacing: -0.01em; }}
      h1 {{ font-weight: 700; }}
      h2, h3 {{ font-weight: 600; }}

      /* --- Page intro (lighter, less framed) --- */
      .pe-intro {{
          display: flex; gap: 1rem; align-items: flex-start;
          padding: 0.75rem 0 1.1rem 0;
          margin-bottom: 1.2rem;
          border-bottom: 1px solid var(--border);
          overflow: visible;
      }}
      .pe-intro .body {{ flex: 1; }}
      .pe-intro .kicker {{
          display: block; max-width: 100%;
          font-size: 0.74rem; font-weight: 600; letter-spacing: 0;
          color: var(--brand); text-transform: none; margin-bottom: 0.25rem;
          line-height: 1.55; white-space: normal; overflow-wrap: normal;
          overflow: visible;
      }}
      .pe-intro .title {{
          font-size: 1.55rem; font-weight: 700; color: var(--text);
          margin-bottom: 0.35rem; line-height: 1.2;
      }}
      .pe-intro .tagline {{
          color: var(--text-muted); font-size: 0.96rem; line-height: 1.5;
          margin-bottom: 0.65rem;
      }}
      .pe-chips {{ display: flex; flex-wrap: wrap; gap: 0.4rem; }}
      .pe-chip {{
          font-size: 0.78rem; color: var(--text-muted);
          background: var(--surface-2); border: 1px solid var(--border);
          padding: 0.18rem 0.55rem; border-radius: 8px;
      }}

      /* --- Insight cards (full-width row block) --- */
      .pe-insight {{
          display: flex; flex-direction: column; gap: 0.3rem;
          padding: 0.9rem 1rem; border-radius: 8px;
          border: 1px solid var(--border); border-left-width: 3px;
          background: var(--surface-card); height: 100%;
      }}
      .pe-insight .label {{
          font-size: 0.72rem; letter-spacing: 0.07em; font-weight: 600;
          text-transform: uppercase;
      }}
      .pe-insight .headline {{
          font-size: 1.05rem; font-weight: 600; color: var(--text);
          line-height: 1.3;
      }}
      .pe-insight .detail {{
          font-size: 0.85rem; color: var(--text-muted); line-height: 1.4;
      }}

      /* --- Status pills --- */
      .pe-pill {{
          display: inline-block; padding: 0.15rem 0.55rem; border-radius: 999px;
          font-size: 0.75rem; font-weight: 600; letter-spacing: 0.02em;
          border: 1px solid transparent;
      }}

      /* --- Section header --- */
      .pe-section {{
          margin: 1.4rem 0 0.5rem 0; padding-bottom: 0.35rem;
          border-bottom: 1px solid var(--border);
      }}
      .pe-section .title {{ font-size: 1.1rem; font-weight: 600; color: var(--text); }}
      .pe-section .caption {{ font-size: 0.85rem; color: var(--text-muted); margin-top: 0.1rem; }}

      /* --- Sidebar brand --- */
      section[data-testid="stSidebar"] .pe-brand {{
          padding: 0.4rem 0 0.8rem 0;
          border-bottom: 1px solid var(--border); margin-bottom: 0.8rem;
      }}
      section[data-testid="stSidebar"] .pe-brand .name {{
          font-size: 1.02rem; font-weight: 700; color: var(--text);
      }}
      section[data-testid="stSidebar"] .pe-brand .tag {{
          font-size: 0.78rem; color: var(--text-muted);
      }}
      section[data-testid="stSidebar"] .pe-badges {{
          display: flex; flex-wrap: wrap; gap: 0.3rem; margin-top: 0.4rem;
      }}
      section[data-testid="stSidebar"] .pe-badge {{
          display: inline-block; padding: 0.15rem 0.5rem; border-radius: 4px;
          background: var(--surface-2); border: 1px solid var(--border);
          font-size: 0.78rem; color: var(--text);
      }}
      section[data-testid="stSidebar"] .pe-nav {{
          font-size: 0.88rem; color: var(--text-muted); line-height: 1.55;
      }}
      section[data-testid="stSidebar"] .pe-nav .step {{ color: var(--brand); font-weight: 600; }}

      section[data-testid="stSidebar"] .pe-nav-label {{
          font-size: 0.72rem; font-weight: 650; letter-spacing: 0.06em;
          text-transform: uppercase; color: var(--text-muted);
          margin: 0.35rem 0 0.25rem 0;
      }}
      section[data-testid="stSidebar"] .pe-sidebar-footer {{
          margin-top: auto;
          padding-top: 1rem;
          border-top: 1px solid var(--border);
          font-size: 0.78rem;
          color: var(--text-muted);
          line-height: 1.45;
      }}
      section[data-testid="stSidebar"] .pe-sidebar-footer .name {{
          color: var(--text);
          font-weight: 650;
      }}
      section[data-testid="stSidebar"] .pe-sidebar-footer a {{
          color: var(--brand);
          text-decoration: none;
          font-weight: 600;
      }}
      section[data-testid="stSidebar"] .pe-sidebar-footer a:hover {{
          text-decoration: underline;
      }}

      /* Make Streamlit's native alerts feel less shouty when we still use them */
      [data-testid="stAlert"] {{ border-radius: 8px; }}

      /* Metric tightening */
      [data-testid="stMetricValue"] {{ font-weight: 700; color: var(--text); }}
      [data-testid="stMetricLabel"] {{ color: var(--text-muted); font-weight: 500; }}
    </style>
    """


def apply_page_theme() -> None:
    """Inject CSS + register Plotly template. Call once per page."""
    if not st.session_state.get('_pe_theme_applied'):
        register_plotly_template()
        st.session_state['_pe_theme_applied'] = True
    st.markdown(_css(), unsafe_allow_html=True)


# ---------------------------------------------------------------------------
# Component helpers
# ---------------------------------------------------------------------------
def _escape(text: str) -> str:
    return (text.replace('&', '&amp;')
                .replace('<', '&lt;')
                .replace('>', '&gt;'))


def page_intro(*, kicker: str, title: str, tagline: str,
               chips: Optional[Iterable[str]] = None,
               icon: Optional[str] = None) -> None:
    """Render a consistent page header block.

    kicker — small uppercase label (e.g. "Step 03 · Test a change")
    title  — plain page title
    tagline — one-line positioning
    chips  — optional list of short "what you can do here" items
    icon  — accepted for back-compat but no longer rendered. Hero emoji was
            removed in v0.6 polish; the kicker line carries the step marker.
    """
    del icon  # intentionally unused
    chip_html = ''
    if chips:
        chip_html = '<div class="pe-chips">' + ''.join(
            f'<span class="pe-chip">{_escape(c)}</span>' for c in chips
        ) + '</div>'
    st.markdown(
        f"""
        <div class="pe-intro">
          <div class="body">
            <div class="kicker">{_escape(kicker)}</div>
            <div class="title">{_escape(title)}</div>
            <div class="tagline">{_escape(tagline)}</div>
            {chip_html}
          </div>
        </div>
        """,
        unsafe_allow_html=True,
    )


@dataclass
class Insight:
    label: str
    headline: str
    detail: str
    tone: str = 'brand'   # 'ok' | 'warn' | 'alert' | 'note' | 'brand' | 'neutral'


def _insight_html(card: Insight) -> str:
    fg_key, bg_key = _TONE_CLASSES.get(card.tone, _TONE_CLASSES['brand'])
    fg, bg = PALETTE[fg_key], PALETTE[bg_key]
    return (
        f'<div class="pe-insight" style="background:{bg};border-left-color:{fg};">'
        f'  <div class="label" style="color:{fg};">{_escape(card.label)}</div>'
        f'  <div class="headline">{_escape(card.headline)}</div>'
        f'  <div class="detail">{_escape(card.detail)}</div>'
        f'</div>'
    )


def insight_row(cards: Iterable[Insight]) -> None:
    """Render 2–4 insight cards side-by-side in equal columns."""
    cards = list(cards)
    if not cards:
        return
    cols = st.columns(len(cards))
    for col, card in zip(cols, cards):
        with col:
            st.markdown(_insight_html(card), unsafe_allow_html=True)


def status_pill(text: str, tone: str = 'neutral') -> str:
    """Return an inline HTML pill. Call with ``st.markdown(..., unsafe_allow_html=True)``."""
    fg_key, bg_key = _TONE_CLASSES.get(tone, _TONE_CLASSES['neutral'])
    fg, bg = PALETTE[fg_key], PALETTE[bg_key]
    return (f'<span class="pe-pill" style="color:{fg};background:{bg};'
            f'border-color:{fg}33;">{_escape(text)}</span>')


def section_header(title: str, caption: Optional[str] = None) -> None:
    cap_html = f'<div class="caption">{_escape(caption)}</div>' if caption else ''
    st.markdown(
        f'<div class="pe-section"><div class="title">{_escape(title)}</div>{cap_html}</div>',
        unsafe_allow_html=True,
    )


# ---------------------------------------------------------------------------
# Sidebar branding
# ---------------------------------------------------------------------------
def sidebar_brand(*, name: str, tag: str,
                  badges: Optional[Iterable[tuple[str, str]]] = None,
                  workflow: Optional[Iterable[tuple[int, str, bool]]] = None) -> None:
    """Render the branded sidebar header.

    badges — iterable of (label, value) pairs rendered as plain-text chips.
             Labels should be business language (e.g. 'Price sensitivity'),
             not Greek letters.
    workflow — accepted for back-compat but no longer rendered. Streamlit's
               native multipage sidebar nav already lists pages; rendering
               a static workflow on top produces a confusing dual nav.
    """
    del workflow  # intentionally unused
    with st.sidebar:
        badges_html = ''
        if badges:
            badges_html = '<div class="pe-badges">' + ''.join(
                f'<span class="pe-badge">{_escape(lbl)} {_escape(val)}</span>'
                for lbl, val in badges
            ) + '</div>'
        st.markdown(
            f"""
            <div class="pe-brand">
              <div class="name">{_escape(name)}</div>
              <div class="tag">{_escape(tag)}</div>
              {badges_html}
            </div>
            """,
            unsafe_allow_html=True,
        )
        st.markdown('<div class="pe-nav-label">Navigate</div>', unsafe_allow_html=True)
        for path, label in SIDEBAR_PAGES:
            st.page_link(path, label=label)
        st.markdown(
            f"""
            <div class="pe-sidebar-footer">
              <div>Built by</div>
              <div class="name">{_escape(AUTHOR_NAME)}</div>
              {f'<div>{_escape(AUTHOR_AFFILIATION)}</div>' if AUTHOR_AFFILIATION else ''}
              <div style="margin-top:0.45rem;">
                <a href="{GITHUB_URL}" target="_blank" rel="noopener noreferrer">
                  GitHub repository ↗
                </a>
              </div>
            </div>
            """,
            unsafe_allow_html=True,
        )
